### ISSUE TITLE
vsc_ace command IPU_OWN_CAMERA(19) response timeout

### ISSUE THREAD

**Issue by vicamo** [intel/ivsc-driver#47]
This is observed on both 6.5 (therefore ivsc-dkms) and 6.8 (therefore in-tree ivsc). Even I doubled the timeout to 10 seconds, it can still fail with the same timeout error.
```
[   15.201368] vsc_ace spi-INTC10D0:00-5db76cf6-0a68-4ed6-9b78-0361635e2447: recv firmware id
[   20.271361] vsc_ace spi-INTC10D0:00-5db76cf6-0a68-4ed6-9b78-0361635e2447: command 19 response timeout
[   20.271376] ipu own camera failed
[   20.379072] ov02c10 i2c-OVTI02C1:00: Acquire VSC failed
[   20.379522] ov02c10: probe of i2c-OVTI02C1:00 failed with error -110
```

**Comment by wentongwu** [comment]
```
diff --git a/drivers/misc/ivsc/intel_vsc.c b/drivers/misc/ivsc/intel_vsc.c
index 40ec0d5..55c5ca0 100644
--- a/drivers/misc/ivsc/intel_vsc.c
+++ b/drivers/misc/ivsc/intel_vsc.c
@@ -178,7 +178,7 @@ int vsc_acquire_camera_sensor(struct vsc_mipi_config *config,
 
 err:
        mutex_unlock(&vsc.mutex);
-       msleep(100);
+       msleep(500);
        return ret;
 }
 EXPORT_SYMBOL_GPL(vsc_acquire_camera_sensor);
```

@vicamo I never saw this problem on our RVP platform, but could you please help try this patch? Thanks

**Comment by vicamo** [comment]
> drivers/misc/ivsc/intel_vsc.c

Have you tried this by your own? That's to increase a sleep period _after_ the problem occurred.

**Comment by wentongwu** [comment]
> > drivers/misc/ivsc/intel_vsc.c
> 
> Have you tried this by your own? That's to increase a sleep period _after_ the problem occurred.

I can't reproduce the issue, can you share more info about your environment (e.g. kernel version)?

and please don't mix the github code with upstream code, if you use github code, please do not include any upstream code.

BTW, did you get any chance to try the upstream code, I know @hao-yao successfully enabled it.

**Comment by vicamo** [comment]
> > > drivers/misc/ivsc/intel_vsc.c
> > 
> > 
> > Have you tried this by your own? That's to increase a sleep period _after_ the problem occurred.
> 
> I can't reproduce the issue, can you share more info about your environment (e.g. kernel version)?

This is observed on both 6.5 (therefore ivsc-dkms) and 6.8 (therefore in-tree ivsc).

> and please don't mix the github code with upstream code, if you use github code, please do not include any upstream code.

https://github.com/intel/ivsc-driver/blob/b5969f9311c07a80250c3ab5e1174a792195e8e3/drivers/misc/ivsc/intel_vsc.c#L179
Do you even know what you're saying? There is no `vsc_acquire_camera_sensor` in upstream code at all.

> BTW, did you get any chance to try the upstream code, I know @hao-yao successfully enabled it.

**Comment by wentongwu** [comment]
> > > > drivers/misc/ivsc/intel_vsc.c
> > > 
> > > 
> > > Have you tried this by your own? That's to increase a sleep period _after_ the problem occurred.
> > 
> > 
> > I can't reproduce the issue, can you share more info about your environment (e.g. kernel version)?
> 
> This is observed on both 6.5 (therefore ivsc-dkms) and 6.8 (therefore in-tree ivsc).
> 
> > and please don't mix the github code with upstream code, if you use github code, please do not include any upstream code.
> 
> https://github.com/intel/ivsc-driver/blob/b5969f9311c07a80250c3ab5e1174a792195e8e3/drivers/misc/ivsc/intel_vsc.c#L179
> 
> 
> Do you even know what you're saying? There is no `vsc_acquire_camera_sensor` in upstream code at all.

https://github.com/torvalds/linux/blob/master/drivers/acpi/scan.c#L834

and https://github.com/torvalds/linux/blob/master/drivers/media/pci/intel/ipu-bridge.c which has some code for ivsc upstream code integration

> > BTW, did you get any chance to try the upstream code, I know @hao-yao successfully enabled it.

**Comment by wentongwu** [comment]
@vicamo do you know what's the changes here https://bugs.launchpad.net/somerville/+bug/1998774/comments/60?
